### ISSUE TITLE
如何显示秒?

### ISSUE THREAD

**Issue by crapthings** [pragmaticly/smart-time-ago#14]
showSeconds: true

这个参数好使吗？

**Comment by poshboytl** [comment]
没太懂你的意思... 你希望现实 几秒以前？

**Comment by crapthings** [comment]
是啊， 现在这个功能好使吗？

**Comment by poshboytl** [comment]
没有做..这个不是普遍需求…而且这样 你需要每秒钟去做更新 …你需要的话可以fork 自己实现一个版本… :)

## Terry Tai

Co-founder of Pragmatic.ly
Creator of Railscasts-china
skype: terrytie
gtalk: poshboytl@gmail.com
twitter: poshboytl
phone: (+86) 18602826749

在 2012年10月16日星期二，下午9:21，crapthings 写道：

**Comment by crapthings** [comment]
还有一个问题，现在中文版怎么回事，比如我发一条信息，然后当发送成功时候 callback 用这个 timeago时候 那里时间为什么显示   “大约 分钟之前”  不能显示 不到一分钟之类的吗？

秒就显示 大约30秒之前 也可以啊。不用每秒都显示，或者显示个不到一分钟，中文版现在显示的 大约 分钟之前
感觉好像是没显示时间，还是说这是翻译问题？
