### ISSUE TITLE
"Ago" is a prefix in other languages (french for example)

### ISSUE THREAD

**Issue by younes0** [pragmaticly/smart-time-ago#7]
In french, we would say "ago 2 hours" (il y a 2 heures).
Could you provide an option to allow this please ?

**Comment by poshboytl** [comment]
Oh.. I think you are right. I might need add something like prefixAgo.

**Comment by poshboytl** [comment]
oops... Why you close it? :)

**Comment by nicooprat** [comment]
+1 for this !
